name: Automated Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to create releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare release assets
        run: |
          mkdir release_assets
          cp modules/release/* release_assets/
          zip -r release_assets/server_bundle.zip start_server.py template README.md

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
