name: Automated Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare release assets
        run: |
          mkdir release_assets
          
          # Copy all files from modules/release individually
          cp modules/release/* release_assets/
          
          # Create a zip with start_server.py, template/, and README.md
          zip -r release_assets/server_bundle.zip start_server.py template README.md

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
